---
title: "Publications"
---
***

Fan, J., Woodworth, K., Murphy, K.R., Hinkley, L., Cohen, J.L., Yoshimura, J.,  Choi, J., __Tremblay-McGaw, A.G.__, Mergenthaler, J., Good, C.H., Pellionisz, P.A., Lee, A.M., Ianni, T.D., Sugrue, L.P., & Krystal, A. (in submission). Thalamic low intensity focused ultrasound stimulation in treatment resistant depression.

__Abstract__

_Coming soon!_


***

__Tremblay-McGaw, A.G.__, Biggs, E.E., Timmers, I., Moulton, E., & Simons, L.E., (in preparation). The role of the cerebellum in threat learning in youth with chronic pain.

__Abstract__

_Coming soon!_


***

Biggs, E.E., Heathcote, L.C., Timmers, I., __Tremblay-McGaw, A.G.__, Noel, M., Borsook, D., & Simons, L.E., (under review). Testing the boundary conditions of emotional memory bias: A multi-method examination in adolescents with chronic pain.

__Abstract__

_Coming soon!_


***

__Tremblay-McGaw, A.G.__, Biggs, E.E., Sokol, O., Wiseman Miner, A., Goya Arce, A., & Simons, L.E., (under review). Who is being represented in research? A framework for assessing diversity and representation in prospective research cohorts.

__Abstract__

While there are an increasing number of steps being taken to address a lack of representation in research populations, the data needed to facilitate these steps, and fully evaluate current research, is still lacking. In this paper we propose a framework that allows researchers to engage with this process in a small-scale and inexpensive way, by reporting population level characteristics alongside standard participant descriptors. As an example, we examined differences between adolescents with chronic pain who decided to enroll in a large biomarker study and those who were eligible but decided not to enroll. Here, we focused on demographics, pain characteristics, mental health, functioning, and caregiver profiles. We propose that by engaging in such checkpoints, readers can better assess the generalizability of findings, and we can begin to address discrepancies and barriers in research.


***

Timmers, I., Bruckert, L., Biggs, E.E., __Tremblay-McGaw, A.G.__, Borsook, D., Zhang, H., & Simons, L.E. (2024). Probing white matter microstructure in youth with chronic pain and its relation to catastrophizing using neurite orientation dispersion and density imaging. PAIN ():10.1097/j.pain.0000000000003269, May 8, 2024.

__Abstract__

Chronic pain is common in young people and can have a major life impact. Despite the burden of chronic pain, mechanisms underlying chronic pain development and persistence are still poorly understood. Specifically, white matter (WM) connectivity has remained largely unexplored in pediatric chronic pain. Using diffusion-weighted imaging, this study examined WM microstructure in adolescents (age M = 15.8 years, SD = 2.8 years) with chronic pain (n = 44) compared with healthy controls (n = 24). Neurite orientation dispersion and density imaging modeling was applied, and voxel-based whole-white-matter analyses were used to obtain an overview of potential alterations in youth with chronic pain and tract-specific profile analyses to evaluate microstructural profiles of tracts of interest more closely. Our main findings are that (1) youth with chronic pain showed widespread elevated orientation dispersion compared with controls in several tracts, indicative of less coherence; (2) signs of neurite density tract-profile alterations were observed in several tracts of interest, with mainly higher density levels in patients; and (3) several WM microstructural alterations were associated with pain catastrophizing in the patient group. Implicated tracts include both those connecting cortical and limbic structures (uncinate fasciculus, cingulum, anterior thalamic radiation), which were associated with pain catastrophizing, as well as sensorimotor tracts (corticospinal tract). By identifying alterations in the biologically informative WM microstructural metrics orientation dispersion and neurite density, our findings provide important and novel mechanistic insights for understanding the pathophysiology underlying chronic pain. Taken together, the data support alterations in fiber organization as a meaningful characteristic, contributing process to the chronic pain state.


***

Simons, L.E., Hess, C.W., Choate, E.S., Van Orden, A.R., __Tremblay-McGaw, A.G.__, Menendez, M., Boothroyd, D.B., Griffin, A., Parvathinathan, G., Griffin, A., Caruso, T.J., Stinson, J., Weisman, A., Liu, T., Christensen, R., & Koeppen, K., (2022). Virtual Reality Augmented Physiotherapy for Chronic Pain in Youth: Protocol for a randomized controlled trial enhanced with single case experimental design. Journal of Medical Internet Research. 11(12):e40705.
[PDF](pdfs/SimonsEtal2022.pdf)

__Abstract__

Chronic musculoskeletal (MSK) pain is a prominent health concern, resulting in pain-related disability, loss of functioning and high healthcare costs. Physiotherapy rehabilitation is a gold standard treatment for improving functioning in youth with chronic MSK. However, increasing physical activity can feel unattainable for many adolescents due to pain related fear and movement avoidance. Virtual reality (VR) offers an immersive experience that can interrupt the fear-avoidance cycle and improve engagement in physiotherapy. Despite promising initial findings, data are limited and often lack the rigor required to establish VR as an evidence-based treatment for MSK pain. This trial evaluates pain rehabilitation virtual reality (PRVR) for adolescents with MSK pain. This protocol paper outlines the rationale, design, and implementation of a two-group randomized control trial (RCT) enhanced with Single Case Experimental Design (SCED). The objective of this RCT is to test this advancement in VR technology by providing new treatment solutions targeting nonpharmacological movement facilitation. Primary outcomes include physical function and engagement in VR. Secondary outcomes include pain-related fear and treatment adherence. Significant breakthroughs for treating MSK pain require mechanistically informed innovative approaches. PRVR provides exposure to progressive challenge, real-time feedback, reinforcement for movement and can include activities difficult to achieve in the real world. It has the added benefits of sustaining patient motivation and adherence while enabling clinicians to use objective benchmarks to influence progression. These findings will inform the decision of whether to proceed with a hybrid effectiveness-dissemination trial of PRVR, serving as the basis for potential large-scale implementation of PRVR.


***

Chanales, A.J.H., __Tremblay-McGaw, A.G.__, Drascher, M.L., & Kuhl, B.A. (2020). Adaptive Repulsion of Long-Term Memory Representations Is Triggered by Event Similarity. Psychological Science. 32 (5), 705-720. [PDF](pdfs/ChanalesEtal2021.pdf)

__Abstract__

We tested whether similarity between events triggers adaptive biases in how those events are remembered. We generated pairs of competing objects that were identical except in color and varied the degree of color similarity for the competing objects. Subjects (N = 123 across four experiments) repeatedly studied and were tested on associations between each of these objects and corresponding faces. As expected, high color similarity between competing objects created memory interference for object–face associations. Strikingly, high color similarity also resulted in a systematic bias in how the objects themselves were remembered: Competing objects with highly similar colors were remembered as being further apart (in color space) than they actually were. This repulsion of color memories increased with learning and served a clear adaptive purpose: Greater repulsion was associated with lower associative-memory interference. These findings reveal that similarity between events triggers adaptive-memory distortions that minimize interference.

***
